[[updates]]
version = "1.1.0"
timestamp = 1682820932.624647

[updates.changes]
add = [ "mods/test.jar", "mods/bar.jar", "mods/recursion/recursion/blargh.jar", "config/new_file.cfg",]
rem = [ "config/recursion/depth_test.cfg", "config/foo.cfg",]
[[updates]]
version = "1.0.1"
timestamp = 1674730800.0

[updates.changes]
add = [ "config/recursion/depth_test.cfg",]
rem = []
[[updates]]
version = "1.0.0"
timestamp = 1674730800.0

[updates.changes]
add = [ "mods/foo.jar", "config/foo.cfg",]
rem = [ "mods/bar.jar", "config/bar.cfg",]
